import assert from 'node:assert/strict'
import { readFile, writeFile } from 'node:fs/promises'
import { createClientPlugin } from '../src/client.js'
const manifest = JSON.parse(await readFile(new URL('../package.json', import.meta.url), 'utf8'))
const catalog = JSON.parse(await readFile(new URL('../src/catalog.json', import.meta.url), 'utf8'))
const reference = JSON.parse(await readFile(new URL('../src/cli-reference.json', import.meta.url), 'utf8'))
const models = catalog.data.map(({ id, name, context_length }) => ({ id, name: name || id, contextWindow: context_length }))
const output = `// Generated by scripts/build-client.mjs; edit src/client.js instead.\nwindow.__ModuleLoader__.load({\n  id: ${JSON.stringify(manifest.name)},\n  factory(require) {\n    return (${createClientPlugin.toString()})(require('react'), ${JSON.stringify(models)}, ${JSON.stringify(reference)});\n  },\n});\n`
if (process.argv.includes('--check')) {
  assert.equal(await readFile(new URL('../client.js', import.meta.url), 'utf8'), output, 'client.js is stale: run npm run build and commit it')
  console.log('Committed browser artifact matches its source and catalogues.')
} else {
  await writeFile(new URL('../client.js', import.meta.url), output)
  console.log(`Built ${manifest.name} settings client (${models.length} bundled models).`)
}
